client/main.lua

In our server, we define the events for our items in separate scripts outside of `linden_inventory`.
With the new functionality that allows cancellation of item usage, we need to be able to access the status of `cancelled` in our other scripts to make use of this new functionality. Adding this export allows us to retrieve the value of `cancelled` from an external script, and allows us to continue to define our item events in external scripts via something like:
```
RegisterNetEvent('foo:bar')
AddEventHandler('foo:bar', function(item, wait, cb)
cb(true)
SetTimeout(wait, function()
if not exports["linden_inventory"]:itemCancelled() then
print('do something')
end
end)
end)
```

add an export for cancelled so value can be read in other scripts

---

client/main.lua
config.lua
shared/shops.lua

Not sure if this is something you wan't to implement into the core code. But this is a good base for implementing bt-target directly into the inventory (since people seem to like doing that).
**Added:**
- Config for enabling / disabling.
- Width / Length of bt-target in shops.lua
- Opening of shop through bt-target in client/main.lua

bt-target Support for Shops

---

client/main.lua
server/main.lua
shared/shops.lua
shared/stashes.lua

- Fixes
- Resolved error when buying with dirty money
- Resolved item use getting locked when trying to reload a gun without ammo
- Check if ped is armed with a melee weapon, rather than in melee combat, to reduce durability
- Changes
- Update ESX.PlayerData.inventory as items are moved
- Register keybinds and hotkeys after the inventory has fully loaded
- Update currentWeapon slot if it is moved to ensure correct data sync

feat+fixes: Refresh item data as it moves; weapon-related fixes; other

---

client/main.lua

When they stop holding their hand up while other player is not a cop it will close. Before it would only close if they went out of reach.

Target inventory closing on conditions fix

---

web/src/index.scss

`text-overflow: ellipsis;` doesn't work without setting overflow to hidden.

fix(css): long labels have now working ellipsis

---

modules/shops/server.lua

This was missing, now items in shops can have individual grade requirements.

fix(shops): Add missing grade for slots

---

server.lua
web/src/components/inventory/InventorySlot.tsx

Sometimes when you purchase an weapon and use it, it would show a durability bar on the item in the shop inventory.

fix(shops): Remove durability bar on shop items

---

server.lua

Referring to [this issue](https://trello.com/c/wcjYaqMD/65-creating-drops-ignores-count) on the Trello page.

fix(server): Add count to creating drops

---

data/items.lua
modules/inventory/server.lua
modules/shops/server.lua
server.lua

I think that's a must have to be able to prevent a player to carry more than X quantity of an item, even if the weight capacity is ok.
It's probably not the best way to do it at all, I'm a complete beginner, but at least you get the idea.
For example, you don't want to see a player with 15 heist bags in his inventory.
Or if you want to physically attach a chicken to the hand of a player when he just catched one from the farm.
PS: This was tested in `shops`, `trunks`, `gloveboxes`, and `give` feature with 3 players on the server. No issue for us, except when you `/steal` someone, didnt found where to put the limit (because of time, I work f*ing slowly ^^)

Limit the quantity for an item (Optional)

---

client.lua

This adds an export of the Inventory's `UseSlot` function.
**Use Case**
I was writing a script where I wanted to force equip a weapon with its components. I found no real way to do this without copying a bunch of logic from the `UseSlot` function into my own script, which did not make any sense really.
I have therefore exported and used the `UseSlot` function directly.
Up to you on whether you believe this is useful or not, but I found it useful for my own script, so hopefully others will as well.

Export inventory UseSlot function

---

modules/inventory/server.lua

Fixed the `Confiscate` export to use `Inventory.Confiscate`  and not `Inventory.Return`. Guess someone was sleepy 😂

Confiscate Export

---

server.lua

`/clearevidence` command deletes inventories with `evidence` prefix, not `police`.
Maybe it's better to use `police`, because somebody can already have database entires with this prefix, but I chose `evidence` as it makes more sense for future references.
Swap it if you want.

fix(server): Use "evidence" as name for evidence

---

client.lua

Tired of re-adding, non breaking, use if desired.

Utilize Ped Config Flag checking for Cuff Status

---

client.lua
config.lua
data/shops.lua
data/stashes.lua
modules/init.lua
modules/inventory/server.lua
modules/utils/client.lua
server.lua

You can set up multiple jobs with individual grades. Uses same formats as qtarget:
```lua
police = 'police'
-- or
police = {
police = 0,
sheriff = 2
}
```

feat: Allow multiple police jobs

---

data/locales/cs.lua
data/locales/da.lua
data/locales/de.lua
data/locales/en.lua
data/locales/es.lua
data/locales/fr.lua
data/locales/it.lua
data/locales/nl.lua
data/locales/pt-br.lua
modules/inventory/server.lua
modules/shops/server.lua
server.lua

I made those changes on my server and this is very easier for player to understand what is wrong when trying to swap, buy, give or rob items.
This is also probably better for people because they won't have to handle the notification themself when using `Inventory.CanCarryItem`.
I added locales for each languages but only french is translated.

Better notification when trying to carry too much

---

client.lua
modules/inventory/client.lua
modules/shops/client.lua

Option to have individually different:
- icons for stashes
- labels for shops
- labels for item progressbar

feat(client): Allow individual target icons and labels

---

client.lua

This caused an error when someone created a drop before your inventory loaded (`ox_inventory:setPlayerInventory`).

fix(client): Check if drops are loaded

---

client.lua

Items that only had `export` in client options didn't close the inventory.

fix(client): Close inventory on item use

---

modules/logs/server.lua

Status response is a string, not a number.

Datatype error

---

config.cfg

I guess semicolon is ending the comment so 'whatever' was run as a command and console would output an error on startup

fix: 'whatever' command running as system command

---

modules/items/server.lua
server.lua

Allows containers to contain only specific items set by whitelist or blacklist.
Items listed in `whitelist` table are the only ones that can be moved in the container.
```lua
-- example for wallet
['wallet'] = {
size = {5, 250},
whitelist = {
['money'] = true,
['identification'] = true,
['gymcard'] = true,
['condom'] = true
}
}
```
<br>
Items listed in `blacklist` table cannot be moved in the container.
```lua
-- example for paperbag
['paperbag'] = {
size = {5, 1000},
blacklist = {
['WEAPON_CARBINERIFLE'] = true,
['WEAPON_ADVANCEDRIFLE'] = true,
['WEAPON_SPECIALCARBINE'] = true
}
}
```

feat(server): Restrictions for containers

---

modules/inventory/server.lua

Found a typo that was causing existing inventories stored in the database to not load if they had metadata.

(fix) Typo in Inventory server.lua Fixes #532

---

modules/logs/server.lua

I think it's a good idea to being able to change the datadog hostname, this way you can differentiate one server to an other in your logs (like devServer and LiveServer)
Documentation change : https://github.com/overextended/ox_inventory/pull/556

Add datadog hostname to config

---

docs/index.md

documentation change for my pull request : https://github.com/overextended/ox_inventory/pull/555

add set datadog:hostname to default cfg

---

client.lua
modules/items/server.lua

Lua patterns takes `-` as _0 or more repetitions_.
This fixes issue with consuming items with `ammo` anywhere in the name - e.g. icecre**ammo**chi.

fix: Correct find pattern for ammo

---

data/locales/fr.lua
web/src/components/inventory/InventoryContext.tsx

Without this condition, you can see the button on any weapons (e.g. WEAPON_SWITCHBLADE, which doesn't have any serial number, so it wont copy anything)

Show "Copy serial number" button only if serial exists

---

modules/inventory/server.lua

We have this error if we use additem command with a full inventory

Fix error server.lua136 table index is nil on additem with a full inv

---

modules/inventory/server.lua

Inventory.CanCarryItem had an off-by-one issue because it was checking if newweight >= maxweight, should just be newweight > maxweight so you can actually achieve max weight.
I am unsure if this was done on purpose or was an oversight, so far my testing on my server reveals this works as it should as before this change I could only get up to "maxweight - itemweight" for inventory total weight.

Fix inventory weight check

---

modules/inventory/server.lua

The AddItem cb success variable always returns false, even when successfull, because success is never set to true.

fix(server/inventory): fix AddItem success cb

---

modules/shops/server.lua

Player will now return true if item is free since he can afford it.

fix of 'fix(shop/server): player afford free item'

---

modules/inventory/server.lua

If weight is passed in metadata the CanCarryItem function didnt check it

fix (inventory-server): CanCarryItem

---

client.lua

The hash of VEHICLE_WEAPON_WATER_CANNON is not 1422046295, and the new way is not working. Reverted to the old hash.

Fix fire cannon not working properly

---

web/package.json
web/pnpm-lock.yaml
web/vite.config.ts

Noticed due to Vite it was missing TypeScript checks. The package vite-plugin-checker adds this back.
Also upgraded packages and removed rimraf as it seems unused.

feat(web): vite typescript checks

---

server.lua

* Ran into an issue locally where data being an empty table would lead to ox_inventory thinking there was a malformed inventory that was attempting to be converted

fix(server): Check for empty table

---

modules/bridge/server.lua

Fixes the money change indicator on the inventory showing the wrong amounts and setting the money to the wrong amounts

fix(bridge/server): qb money change

---

modules/inventory/server.lua

**When you swap items from container to inventory you can put overweight item in the container.**
**[Originally](https://streamable.com/2i3tbb)**
**[Edited](https://streamable.com/5cqjmy)**

Fix: putting overweight items in container

---

client.lua

* ~~Appears that pefcl has a conflicting keybind which was~~ Players are unable to reload with default keybind 'R'. Updating the keybind name appears to resolve the issue.

fix(client): Update Reload weapon keybind name

---

modules/inventory/server.lua

Useful thing for creating scripts with metadata weight (filling bottles, buckets and etc.) to not exceed max inventory weight.

feat(modules/inventory/server): CanCarryWeight

---

web/src/components/inventory/InventoryGrid.tsx

Due to the floating point number precision error the inventory weight can be displayed incorrectly.
Example:
This pull request rounds the weight displayed to the player in the inventory GUI down to the nearest gram `0.001` to fix the floating point number precision error being displayed to players. The value in the example would be rounded to `12.765`
This change only affects the GUI displayed to players, not any internal values.

Fix for floating point number precision error in inventory GUI

---

client.lua
modules/inventory/server.lua
modules/items/server.lua
web/src/App.tsx
web/src/components/inventory/InventoryHotbar.tsx
web/src/components/inventory/InventorySlot.tsx
web/src/components/utils/DragPreview.tsx
web/src/components/utils/ItemNotifications.tsx
web/src/store/imagepath.ts
web/src/typings/dnd.ts

This pull request introduces the ability for script creators to include images in their scripts by specifying a web-hosted URL using imgur. This feature can be useful in a variety of situations, such as allowing users to create new menu items on-demand in a business system. I have added an example to the default web development inventory to demonstrate how to use this feature, but it can be removed if desired. In addition, I have implemented the requested changes from Linden, including adding discord logs when an item with a image URL is attempted to be created, implementing a whitelist system for hosts and file types, and adding a new metadata property for the image URL. Please let me know if you have any questions or concerns about these changes.

feat(web): Metadata imageurl support (png & apng)

---

modules/inventory/server.lua

When updating ammo for durability-based weapons, the weapon hash comparison fails because `hash` property does not exist inside the `weapon` table. Hence the ammo for these weapons would not be updated.

fix(weapon): weapon hash check

---

modules/inventory/server.lua

For target inventories being full, use the correct locale that it's the target inventory and not your own.

fix(locale): Use correct locale for target inv

---

modules/inventory/server.lua

fix(modules/inventory/server): wrong maxWeight case

---

client.lua

With some weapons if you roll while reloading it let's you reload faster (e.g. WEAPON_MUSKET) or cause weapon to bug and don't let you to shoot with it (e.g. WEAPON_MINISMG, WEAPON_MACHINEPISTOL).

fix(client): disable rolling while reloading

---

modules/items/server.lua
modules/utils/server.lua

Recently updated to latest and image url seems to be broken due to Utils no longer being loaded, so I updated server utils to follow the same scheme as the client Utils, I tested and this fixed the issue.
Issue PNG
https://i.gyazo.com/87efcac2cb5348ab7c720822502e16be.png

Fix image url being broken

---

modules/shops/server.lua

This fixes the error that is thrown in case `playerInv.open` has more than 1 space occurrence in its string value.
Previously, when the `playerInv.open` value was something like "Cat Cafe Shop 1", the `shopType` would have been "Cat" instead of "Cat Cafe Shop".
Also tested it with global shops so no such https://github.com/overextended/ox_inventory/issues/1146 issue would happen.

fix(module/shops): check for the latest occurrence of space

---

modules/hooks/server.lua

I found an issue with fromInventory being nil when using inventory filter for shops.
Prints being nil
Console error
After fix

Fix(modules/Hooks): Fix shop inventory being nil

---

client.lua
data/items.lua
modules/items/shared.lua
web/src/components/inventory/InventoryContext.tsx

Custom nested buttons. If you like buttons.
Use case: if you have a lot of interactions on an item and you want it to be neatly organized.

feat(client): nested custom context buttons

---

client.lua
modules/crafting/server.lua

- falls back to player position if both points and zones are nil
- untested

feat(crafting): crafting location not required

---

modules/inventory/server.lua

Now matches the check in `Inventory.GetSlotWithItem`

don't check metadata if it's nil

---

modules/mysql/server.lua

Without this it would fail to complete the save and get trapped awaiting a resolution therefore not executing any further saves.

Add missing resolve for stash saving

---

modules/bridge/qb/client.lua

Was thrown error when a QB User was being cuffed with or withount holding a weapon.
https://github.com/overextended/ox_inventory/blob/b7f80a7b12a34558137cd0746c4217cf52d2c1fd/modules/bridge/qb/client.lua#L33

QB Comp - Missing weapons module

---

modules/items/client.lua
web/src/components/inventory/SlotTooltip.tsx
web/src/components/inventory/index.tsx
web/src/store/inventory.ts
web/src/typings/state.ts

- added optional parameter to displayMetadata to specify an order of metadata entries to display. Made some UI code adjustments to change to an array to preserve order.

feat(client): specify displayMetadata order

---

modules/hooks/server.lua

Beforehand it was only possible to use typeFilter on openInventory and BuyItem.
Now its possible to use it everywhere but will only works for fromType and not toType which might be a good idea to add later? idk but for now this would work for most.
Test code for before and after incase anyone wants to test it 🤷 
```lua
exports.ox_inventory:registerHook('swapItems', function(payload)
print(json.encode(payload, { indent = true }))
return false
end, {
print = true,
itemFilter = {
water = true,
},
typeFilter = {
player = true,
}
})
```

Feat(Hooks): Add fromType to typeFilter

---

server.lua

Forceopeninventory export was meant to disable the security checks but it was never passed to the openInventory function

fix (server) forceOpenInventory export fixes

---

modules/inventory/client.lua

fixes an error in https://github.com/overextended/ox_inventory/commit/bf69a767d3db9b5250c68d5f5cf9ccb9c7467faf which caused when attempting to use ox_target on a vehicle as the boneIndex table from data/vehicles.lua was removed

fix(client/inventory): check if boneIndex table is defined

---

modules/shops/client.lua

Im not sure if thats correct, but I stumbled upon that while editing my ox_inventory.
I think its needed, bc if not, even though shop.icon is specified in shops.lua it wont get it when creating the target.

custom icon in data/shop.lua

---

modules/shops/server.lua

Not 100% certain, but Im pretty sure these missing brackets break the randomprices effect if set to false its still random.

randomprices fix

---

modules/inventory/server.lua
modules/shops/server.lua
server.lua

When the inventory logs a action over lib.logger it doesnt send the right source so ox_lib cant create the tags. This is also mentioned in issue #1377

Changed the source thats given to lib.logger

---

modules/inventory/server.lua

Been testing the slot update and it works as expected but my console was spammed by random prints that Luke leftover from his PR

update(inventory/server): remove left over prints

---

modules/bridge/nd/client.lua
modules/bridge/nd/server.lua

nd v1 had `.data` as metadata in v2 it's `.metadata` and there's a function to get specific metadata

fix: nd license check

---

setup/convert.lua

Fixes: https://github.com/overextended/ox_inventory/issues/1566

fix(qb-convert): Utilize old qbinventory metadata.

---

modules/shops/server.lua

Makes it so that the shop message prioritizes the metadata label over the actual item label.
That way there's no conflictions between what the player sees in inventory versus the notify

Feat(shops): Use metadata label over item label

---

modules/bridge/qb/server.lua

QBCore PlayerData name is the steam/fivem name and needs to be overwritten to the name inside charinfo before setPlayerInventory

(bridge:qb) Fix character name not showing on inventory

---

client.lua
modules/weapon/client.lua
server.lua

this adds a new optional param to the useSlot export, it allows for you to disable the anim for weapons if enabled when calling useSlot externally. while this is a little bit niche, i think this can come in handy in any instances where you need to set a weapon to a player immediately.

feat(client/weapons): add useSlot weapon anim skip

---

modules/bridge/qb/client.lua

Fix of issue **[1582](https://github.com/overextended/ox_inventory/issues/1582)**

fix(bridge/qb): "attempt to compare number with boolean" error fix

---

modules/mysql/server.lua

Resolves format error related to save logs accidently introduced within https://github.com/overextended/ox_inventory/commit/3bd6fa855854e0d94dfff80bd48fb2dea5e89f46

fix(server/mysql): inv save format error

---

server.lua

Send entity net ID in `openInventory` hook payload. Useful for additional security checks when opening  trunks, for example.

feat(server): add netid to openInventory hook payload

---

init.lua
modules/weapon/client.lua

Added `inventory:weaponnotify` convar which sets whether to show item notifications when player equips or holsters a weapon.
Enabled by default.

feat(modules/weapons): add convar to disable weapon item notifications

---

modules/inventory/server.lua

The change speaks for itself. Currently the value is not rouned, because the value is not set. This fixes that.

fix(server): Fix rounding number in 'Inventory.Set'

---

modules/inventory/server.lua

This removes the 'cannot_carry' notification in CanCarryItem. It doesn't seem the right place to put the notification. When I use the export to check if a player can carry an item, it sometimes gives 2 notifications because of my own (notification) logic. There might also be cases where you want no notification at all.

fix(server): Remove notification in CanCarryItem

---

modules/inventory/client.lua

It doesn't really make sense to do 'TaskTurnPedToFaceCoord' in the trunk check. Because its called when actually opening the trunk anyway.
Also when you have the 'inventory:target' convar enabled, this function is used to determine if the target option should appear, but at the same time the 'TaskTurnPedToFaceCoord' native gets repeatedly called.

fix(client): Don't turn ped in 'Inventory.CanAccessTrunk'

---

web/src/reducers/setupInventory.ts

Sometimes the shift key gets stuck when for example someone alt-tabs while holding the shift key. This 'stuck' state might lead to confusion, because of the stack-split.
The fix resets the 'shiftPressed' when (re-)opening the inventory.
If there is a better solution, please let me know.

fix(web): Reset 'shiftPressed' in inventory setup

---

modules/bridge/qb/client.lua

The current bridge code toggles handcuff status when receiving a handcuff event from QB. However without the context on whether the player is currently handcuffed this leads to the inventory setting cuffed status when they are actually being uncuffed or vise versa. This can be seen when relogging while cuffed for example, as the inventory doesn't persist the cuffed status, but QB would.
This PR sets cuffed status based on the player's QB metadata (source of truth) fixing the above sync issue, and aligning it with the same way the bridge handles other aspects of player data.
I'm still concerned there may be a race condition, where when the player loads in while cuffed, the inventory won't have loaded before the initial metadata is set, but metadata is likely updated every few seconds due …

fix(bridge/qb): improved handcuff status syncing

---

client.lua
modules/bridge/client.lua
modules/items/client.lua
modules/weapon/client.lua

After using a parachute, the object is created on the players back and the gadget/weapon is given to the player.
However if the player equips another weapon and then unequips it he loses the parachute. It is implemented in `Weapon.ClearAll` but not `Weapon.Disarm`
- Added a check if `client.parachute` is not false and then equips it again after unequipping a weapon
- Refactored the structure & functionning of `client.parachute` to the following:
- Convert it from just containing the object handle but also the tint index in an array, allows the parachute to have the same tint after disarm is called

Fix parachute removed after Disarming a weapon

---

modules/inventory/server.lua

Not sure if anyone else is using this for their own inventory logs system, but we would love to know who dropped something and who picked up something.
By initiating this dropId earlier, we can access this in the "SwapInventory" hook.
Since people might use "newdrop" I haven't change that to the drop-id.

Drop ID in SwapItems hook

---

modules/bridge/qbx/server.lua

This covers setting the account data for multiple money types i.e money and black_money as defined by the inventory:accounts convar

feat(bridge/qbx): sync dynamic account types

---

modules/inventory/server.lua

Adding the stash coords to the inventory data because now you can open stash everywhere you want even if you provide coords in RegisterStash

fix(modules/inventory): stash coords

---

modules/bridge/qbx/server.lua

Corrects issue with inv.items not being pushed into PlayerData.items which is needed by some resources.

fix(bridge/qbx): sync inventory items to player object

---

modules/bridge/qbx/server.lua

This fixes an issue where the plate prefix would resolve via a partial match to the database id in the SQL query. This resulted in random NPCs vehicles providing illegal inventory access to player owned vehicles based off a partial plate match to the id.

fix(bridge/qbx): default NPC vehicle database id to nil

---

modules/shops/client.lua

Solved two issues:
- where the targeting of a ped didn't have a fallback option.
- where the targeting of a zone always had the shopping basket icon (even if a different one was set)

fix: Shop Generation Icons for target

---

modules/crafting/server.lua

- Synchronization of slots, that despite being used in craft still have same amount in UI as before the craft (the amount is not being updated for the UI, unless the slot with item is dragged). 
For me, It didn't work when and not the whole item, but only a part of its durability was used and therefore a new item with new durability was added to another slot, but the amount of items in the initial one remained the same as before craft.

Item amount bug after crafting

---

modules/mysql/server.lua

previous state would throw `bad argument #1 to 'format' (number expected, got string)` as it expect the first argument to be number and not string

fix(server/mysql): fix stashes saving string

---

modules/crafting/server.lua

1 > Properly account for weight changes from durability consumption
2 > Keep server and client weights synchronized
3 > Handle zero durability item removal correctly
4 > Fix the weight discrepancy after multiple crafts

fix(crafting) issue :  #1848 :Weight discrepancy during crafting

---

data/crafting.lua
modules/crafting/server.lua

I've been using this method for a very long time, it's time for me to share hehe
This will make you not have to worry if you create a new crafting in writing random inline code.
In the doc, we need benchId and/or benchIndex for specific bench what we want.
But we will make it easier and safer when making a hook by just giving it its name
This add new parameter for documentation in crafting hooks
> benchName : string (optional)
For usage, just like this
```lua
local hooks = exports.ox_inventory:registerHook('craftItem', function(payload)
if payload.benchName == 'debug_crafting' then
-- add your code for the hooks, maybe logs ?
end
return true
end)
```
Conclusion: This method only helps make it easier for you to create a hook using a pre-set name without having to look at or calculate the …

Make easy crafting hook for ox inventory

---

init.lua
modules/inventory/client.lua
server.lua

This implementation has been tested extensively and worked flawlessly during all tests. The only limitation is that dumpsters need to be frozen when nearby to maintain a consistent position across clients. Given that dumpsters in the game tend to move like cardboard boxes, this could also be considered an improvement haha.
If anyone has suggestions to improve this further, feedback is welcome!

Support for entity lockdown with dumpsters

---

init.lua

Invalid convar for dropweight was set.
setr inventory:dropweight 30000
https://overextended.dev/ox_inventory#config

fix(init.lua): drop weight
