overextended/ox_inventory

- client/main.lua
- html/index.html
- html/script.js
- html/style.css
- server/main.lua
Created a simple give button, checks for the closest player within 3 units. Not the best at front end so may need some touch up for the margins. But it seems to work. If something needs changing let me know
> Added give functionality

- client/main.lua
I added  handsup_enter to the qualifiers for CanOpenTarget
> Added handsup_enter to the qualifiers

- html/script.js
- html/style.css
- set draggable containment to 'parent' instead of 'body'
> Limit draggable item to inventory bounds

- locales/de.lua
> Inserted missing line

- server/main.lua
openinventory event in server/main.lua
> fix some error

- client/main.lua
Fix for bt-target not working.
Now all should work fine.
> bt-target fix

- server/main.lua
The inventory was replacing black money and setting the currency as money, so black_money wouldnt work as a currency. Fixed it
> Fix black money not working as a currency

- html/style.css
Added support for full HD and 4k. Now the inventory rendered in correct size in both resolutions.
> Added 4k Support

- html/script.js
Uses
https://github.com/thelindat/linden_inventory/blob/841e5c6eb96364af3dc14f0e8de102bd99930474/html/script.js#L2
for this part of labeling
> Drop label fix

- client/main.lua
Updated to support changes for my bt-target fork (job access)
> Support for updated my fork for bt-target

- client.lua
- server.lua
- I believe it should be case sensitive based on the file name because in linux it is case sensitive to read file names.
> fix(server): Unable to load due to case sensitive.

- client.lua
> fix(client): Add blur check

- modules/inventory/server.lua
I was testing components, came across this issue.
> fix(inventory/server): Add component to metadata

- client.lua
Apply weapon tint specified in metadata
> feat(client): Apply weapon tint on weapon

- README.md
- As stated in title this PR does replace weirdo `(C)` with `©` in `README.md`
> Replace weird brackets with copyright symbol

- client.lua
- config.lua
- data/locales/cs.lua
- data/locales/da.lua
- data/locales/en.lua
- data/locales/es.lua
- data/locales/fr.lua
- data/locales/it.lua
- data/locales/nl.lua
- data/locales/pt-br.lua
- data/stashes.lua
- data/vehicles.lua
- fxmanifest.lua
- modules/inventory/client.lua
- modules/shops/client.lua
- server.lua
> refactor: Unify indentation and formatting

- modules/inventory/server.lua
Check for inventory ID instead of inventory object or table
> Add check in CanSwapItem for inventory ID

- modules/inventory/server.lua
To reproduce the error, just eat a burger.
You'll get this:
> Fix error when using removable item

- client.lua
- data/animations.lua
- data/items.lua
More changes to help reduce duplicate code and make adjusting animations and props easier if needed across multiple items.
> feat(items): Reusable references for animations and props

- data/items.lua
Did this to make life easier and to trim down on duplicate code.
Not always needed, if you want to build the function yourself, but there if you're lazy
> feat(items): Build item use functions based off client.notification

- client.lua
There is a locale who was waiting for it so let's use it :)
> Notify if use component and not wearing weapon

- data/weapons.lua
> Better durability

- client.lua
- data/vehicles.lua
Added option to disable glovebox or trunk only.
> feat(client): Allow more specific vehicle storage restrictions

- data/locales/en.lua
- modules/inventory/server.lua
> fix(locales): fixed incorrect english locale

- docs/modules/items/create.md
Added new example with add and remove arguments
> notify burger

- client.lua
- modules/init.lua
"features nobody asked for and where to find them" in bookstores anytime soon™
> feat: disable action mode and firing without aiming

- data/locales/si.lua
Fixed some stuff that weren't/wrongfull translated.
> Fixed some stuff in the SI.lua

- client.lua
- data/items.lua
- web/src/components/inventory/InventoryContext.tsx
- web/src/dnd/onCustomButton.ts
- web/src/typings/item.ts
Makes it possible to have multiple built-in interactions with items (_e.g. use rolling paper to make cigarette or joint_).
Preview: https://streamable.com/rytnia
> feat(client): Custom context buttons

- data/locales/pl.lua
- data/locales/pt-br.lua
Closed my last PR & just updated the languages I know, apologies.
> Locales update

- modules/inventory/server.lua
Checks how much of a certain item you can carry so you can give that amount instead of returning false can't carry.
> Added can carry amount

- README.md
Updated the documentation link
> Updated the docs link in the README

- data/weapons.lua
Adding weapon's that are missing. Some are missing a image too.
> feat(weapon): adding missing weapon's

- client.lua
- modules/bridge/client.lua
- modules/bridge/server.lua
- modules/inventory/server.lua
- modules/items/server.lua
- modules/mysql/server.lua
- modules/shops/server.lua
- server.lua
- setup/convert.lua
- setup/vehicle.sql
Yaaay, the long awaited QB support
> QB Support

- client.lua
- modules/bridge/qb/server.lua
- modules/inventory/client.lua
- modules/inventory/server.lua
- modules/utils/client.lua
- setup/convert.lua
This should fix qb compat and fix some things I found whilst suppressing warnings that show when they don't need to, which are IsPedCuffed not having it's only argument defined, the ped to check and GetPedInVehicleSeat not having the vehicle to check defined
> Fixes and warning suppression

- data/items.lua
fixes syntax error that comes from qb/esx item imports
> fix(data/items): comma for item imports

- modules/bridge/qb/server.lua
This should fix the errors when making a new character
> feat(server/bridge/qb): convert inventory function

- fxmanifest.lua
update fxmanifest.lua no more logs
> update fxmanifest.lua no more logs

- modules/shops/client.lua
theres apparently a string limit and the fivem discord has a conversation with bdub saying this is better. I dont have something to test it with currently but figured a pr with it will do. It works fine in qb with everything I throw at it.
> better blips method [UNTESTED]

- server.lua
Since the new code to vehicle access, we can't open glovebox or trunk
> Fix access to glovebox and trunk

- locales/fr.json
Add `not_enough_durability` locale
> chore(locales/fr): updated french translations

- locales/es.json
> Update Interact in spanish

- modules/hooks/server.lua
```lua
ox_inventory:registerHook('openInventory', function(payload)
print('you opened a container')
end, {
typeFilter = {
container = true,
}
})
```
> feat(server/hooks): inventory type filter

- server.lua
```lua
ox_inventory:registerHook('openInventory', function(payload)
if payload.inventoryType == 'container' then
local item = ox_inventory:GetSlot(payload.source, payload.slot)
-- ...
end
end, {
print = true,
})
```
> feat(server): add container slot to hook payload

- modules/bridge/nd/server.lua
groups are already in the correct order there.
> fix: reorderGroups causing error

- data/weapons.lua
Renaming to WEAPON_AUTOSHOTGUN as WEAPON_SWEEPERSHOTGUN does not exist.
> fix(data/weapons): fix invalid weapon data

- client.lua
- locales/en.json
- locales/nl.json
- modules/crafting/client.lua
Adds dutch crafting locales and support for custom label and icon on crafting zones.
Also fixes custom labels for crafting benches as they are used in blips ,but not the inventory title.
> feat(crafting): labels and locales

- modules/inventory/server.lua
This change will be really helpful when using hooks since we will now have full item data that was given. 
This is an answer to this issue : #1164
> Added some extras data in swapItems hook

- modules/items/shared.lua
client?.export -> clientData?.export
server?.export -> serverData?.export
> Fix client export

- modules/shops/server.lua
Currently a grade of a shop item is a number that the player has to be at or above, but by having the option for an array instead of a number, shop items can be available to specific ranks only.
> feat(server/shops): option for grade to be an array of specific grades

- setup/convert.lua
> fear(server/setup): converting qb evidence

- modules/items/server.lua
https://i.imgur.com/x5jwW4m.png
> Fix nil value `metadata`

- modules/bridge/qb/client.lua
> fix(qb/client): prevent inventory access while in last stand state

- modules/bridge/qb/client.lua
> fix(qb/client): qb last stand checking

- modules/bridge/qb/client.lua
For people who use qb's progressbar, and maybe other resources https://github.com/qbcore-framework/progressbar/blob/main/client/main.lua#L113
> feat(bridge/qb): listen for 'inv_busy' state

- locales/de.json
4 Translation were missing in locales/de.json
> Missing Translations in de.json

- data/weapons.lua
> Add some missing weapon skins

- locales/de.json
"storage" was missing in de.json.
> Add Missing Translation in de.json

- modules/bridge/nd/client.lua
- modules/bridge/nd/server.lua
- modules/mysql/server.lua
This is tested on ND 2.0.0 but the update not released yet. It will be done in a few days.
> Support for ND 2.0.0

- modules/items/server.lua
Fixes: https://github.com/overextended/ox_inventory/issues/1569
> Fix(items/server.lua): Serial numbers not being created in stashes

- modules/bridge/nd/client.lua
ND Status was updated & the old character loaded event was changed, the new event is backwards compatible and also works if backwards compatibility is not enabled which is an option in nd.
> tweak(bridge/nd) status values & character loaded event

- web/index.html
- web/src/components/inventory/InventoryGrid.tsx
- web/src/components/inventory/InventorySlot.tsx
- web/src/components/inventory/index.tsx
- web/src/components/utils/ItemNotifications.tsx
- web/src/components/utils/Tooltip.tsx
- web/src/components/utils/WeightBar.tsx
- web/src/components/utils/menu/Menu.tsx
- web/src/components/utils/transitions/Fade.tsx
- web/src/components/utils/transitions/SlideUp.tsx
- web/src/helpers/index.ts
- web/src/hooks/useDebounce.ts
- web/src/hooks/useIntersection.ts
- web/src/hooks/useKeyPress.ts
- web/src/hooks/useQueue.ts
- web/src/reducers/refreshSlots.ts
- web/src/store/inventory.ts
> Minor changes and clean-ups

- modules/bridge/nd/client.lua
- modules/bridge/nd/server.lua
Players groups wasn't updating in inventory
> fix(bridge/nd): updating player data

- server.lua
fix for  `attempt to index a number value (local 'data')` in line 167
> fix(server/openInventory): check if data is a table before accessing it

- client.lua
> fix(client): Fix resetting 'swapActive' value

- web/src/components/inventory/InventorySlot.tsx
fixed datatype errors on build
> fixed datatype

- modules/hooks/server.lua
- modules/shops/server.lua
Added `fromSlot` value to the payload of `buyItem` hook.
This value is useful for people who wants to build additional features on top of the default shop system.
> feat(modules/shops): add fromSlot to buyItem hook payload

- client.lua
This PR patch the https://github.com/overextended/ox_inventory/issues/1695
> fix(client/weapon): notify can not perform

- modules/inventory/server.lua
This change allows for the RemoveItem function to support partial metadata removals.
> feat(server): Allow strict/partial metadata on RemoveItem

- modules/bridge/qbx/client.lua
- modules/bridge/qbx/server.lua
- modules/mysql/server.lua
Adds support for qbx_core. Blocked on https://github.com/Qbox-project/qbx_core/pull/528
> feat: qbx_core support

- modules/inventory/server.lua
- server.lua
You can open owner = true stash with forceopeninventory without the group role
You can open evidence without hasGroup
> ignore checker for private stash access

- client.lua
Fixed a possible problem with the TextUI when buying a license.
Thanks to @hey_im_redacted for noticing.
> fix(client): infinite textui

- locales/fr.json
missing translation for storage
> small update for locales/fr

- locales/tr.json
> Update tr.json - missing ,
